"""Frozen external gates for three complete ISO B3 waveform references.

The B2 third-octave source is acquired for provenance only: the product has no
third-octave-input entry point. Reference values are never generated by the app.
"""
from datetime import datetime, timezone
import hashlib
from importlib.metadata import version
import json
from pathlib import Path
from time import perf_counter

import numpy as np
import pytest
from scipy.io import wavfile

from autoacoustics.analysis.loudness import compute_stationary
from autoacoustics.calibration import apply_calibration
from autoacoustics.importers import import_signal
from autoacoustics.model import CalibrationProfile

ROOT = Path(__file__).resolve().parents[1]
REF = ROOT / 'tests/reference/upstream/stationary_extended'
COMMIT = 'a14daeafcf0a37f36e4a29314ea42bc68b304c0e'
UPSTREAM = 'validations/sq_metrics/loudness_zwst/input/ISO_532_1/'
# Independently recorded from the official fixed Git tree, before acquisition.
FILES = {
    'stationary_signal2_250Hz_80dB.wav': ('Test signal 2 (250 Hz 80 dB).wav', 'e0dd74a2aed336c48b17f15fb0bf81a90f48af36', 960044),
    'stationary_signal3_1kHz_60dB.wav': ('Test signal 3 (1 kHz 60 dB).wav', 'faea4fc752a916beed8ee915e4b0338f78f4464f', 960044),
    'stationary_signal4_4kHz_40dB.wav': ('Test signal 4 (4 kHz 40 dB).wav', '5dde120cee1db3ff59a3de740b15ed0660318246', 960044),
    'stationary_signal2_specific.csv': ('test_signal_2.csv', 'a0342685838e54a08eaef42c256db4f7030ac49d', 1524),
    'stationary_signal3_specific.csv': ('test_signal_3.csv', '10758ffb3ca4ebc95d25f4b16712138fe6c1fc2f', 1623),
    'stationary_signal4_specific.csv': ('test_signal_4.csv', '18331efd959cffc8e42dfdf15850f8b05009818a', 1524),
    'third_octave_signal1.source.txt': ('test_signal_1.py', '7dc59c6920668cd0e49daeac2c9bb4b3a49c36bd', 485),
    'third_octave_signal1_specific.csv': ('test_signal_1.csv', 'afce6b9fff43201c6f100bea7e0d88ae7fdc2d5f', 1726),
}
CASES = {
    2: ('stationary_signal2_250Hz_80dB.wav', 14.655),
    3: ('stationary_signal3_1kHz_60dB.wav', 4.019),
    4: ('stationary_signal4_4kHz_40dB.wav', 1.549),
}
PROVENANCE = {
    'validation_loudness_zwst.py': '209755000dca2e7590cc0f62917ca0d8bb4ca41059fae36f2b8f32024e47be5a',
    'load.py': '2e854c7754b56637afd8497bc37fe07a2bb63d4e1fb156e85afecaa037a7fdb8',
}
# Frozen before first numerical run; no offset, crop, normalization or curve fit.
GATES = {
    'total_sone': 'abs(actual-expected) <= max(0.1, 0.05*abs(expected))',
    'specific_sone_per_bark': 'all 240: abs(actual-expected) <= max(0.1, 0.05*abs(expected))',
    'bark': '240 points 0.1..24.0, absolute error <= 1e-13, relative tolerance 0',
}


def checked_manifest():
    manifest = json.loads((REF / 'manifest.json').read_text(encoding='utf-8'))
    assert manifest['commit'] == COMMIT
    assert manifest['tag'] == 'v1.2.1'
    assert manifest['repository'] == 'https://github.com/Eomys/MoSQITo'
    records = {record['local_file']: record for record in manifest['files']}
    assert len(manifest['files']) == len(records) == 8
    assert records.keys() == FILES.keys()
    for name, (upstream_name, expected_blob, expected_size) in FILES.items():
        record = records[name]
        data = (REF / name).read_bytes()
        assert record['upstream_path'] == UPSTREAM + upstream_name
        assert record['git_blob_sha1'] == expected_blob
        assert record['bytes'] == len(data) == expected_size
        assert hashlib.sha1(f'blob {len(data)}\0'.encode() + data).hexdigest() == expected_blob
        assert hashlib.sha256(data).hexdigest() == record['sha256']
    for name, digest in PROVENANCE.items():
        assert hashlib.sha256((REF.parent / name).read_bytes()).hexdigest() == digest
    assert manifest['b2_signal1']['product_validation'] is False
    assert manifest['b2_signal1']['input_type'] == 'third_octave_levels'
    assert manifest['distribution']['included_in_product_bundle'] is False
    assert manifest['distribution']['reference_data_redistribution_verified'] is False
    return manifest, records


def evaluate_stationary_case(signal_id):
    started = perf_counter()
    manifest, records = checked_manifest()
    name, expected_total = CASES[signal_id]
    path = REF / name
    expected_name = f'stationary_signal{signal_id}_specific.csv'
    expected = np.loadtxt(REF / expected_name, skiprows=1, encoding='utf-8-sig')
    assert expected.shape == (240,)
    assert np.all(np.isfinite(expected)) and np.all(expected >= 0)
    raw_fs, raw_pcm = wavfile.read(path)
    assert raw_pcm.dtype == np.int16 and raw_pcm.shape == (480000,)
    assert raw_fs == 48000
    assert version('mosqito') == '1.2.1'
    signal = import_signal(path)
    assert signal.frames == len(raw_pcm) and signal.channel_count == 1
    assert signal.sample_rate == raw_fs and signal.channels[0].unit == 'FS'
    assert signal.source_hash == records[name]['sha256']
    coefficient = 2 * np.sqrt(2) * 32768 / 32767
    profile = CalibrationProfile(
        'Official stationary reference scaling',
        'Fixed MoSQITo v1.2.1 load.py wav_calib=2*sqrt(2); int16 denominator=32767',
        coefficient, 'FS', applicable_hashes=(signal.source_hash,),
    )
    physical = apply_calibration(signal, profile).samples[0]
    expected_physical = raw_pcm.astype(np.float64) / 32767 * 2 * np.sqrt(2)
    np.testing.assert_allclose(physical, expected_physical, rtol=1e-15, atol=1e-16)
    result = compute_stationary(physical, signal.sample_rate, field_type='free')
    actual_total = result['total']
    actual_specific = np.asarray(result['specific'])
    actual_bark = np.asarray(result['bark'])
    assert actual_specific.shape == actual_bark.shape == (240,)
    assert np.isfinite(actual_total) and actual_total >= 0
    assert np.all(np.isfinite(actual_specific)) and np.all(actual_specific >= 0)
    assert np.all(np.isfinite(actual_bark)) and result['status'] == 'ok'
    total_delta = float(actual_total - expected_total)
    total_limit = max(.1, .05 * abs(expected_total))
    specific_error = np.abs(actual_specific - expected)
    specific_limits = np.maximum(.1, .05 * np.abs(expected))
    violations = int(np.count_nonzero(specific_error > specific_limits))
    bark_error = float(np.max(np.abs(actual_bark - np.arange(1, 241) * .1)))
    gates_passed = {
        'total': abs(total_delta) <= total_limit,
        'all_240_specific': violations == 0,
        'bark': bark_error <= 1e-13,
    }
    return {
        'signal_id': signal_id, 'passed': all(gates_passed.values()),
        'input_file': name, 'input_sha256': records[name]['sha256'],
        'input_git_blob_sha1': records[name]['git_blob_sha1'],
        'reference_file': expected_name, 'reference_sha256': records[expected_name]['sha256'],
        'reference_git_blob_sha1': records[expected_name]['git_blob_sha1'],
        'Nexpected_sone': expected_total, 'Nactual_sone': actual_total,
        'Ndelta_sone': total_delta, 'Nabsolute_limit_sone': total_limit,
        'specific_values_checked': 240, 'specific_max_absolute_error_sone_per_bark': float(np.max(specific_error)),
        'specific_outside_frozen_limit_count': violations,
        'bark_max_absolute_error': bark_error, 'gates_passed': gates_passed,
        'field_type': 'free', 'sample_rate_hz': raw_fs, 'frames': len(raw_pcm),
        'channels': 1, 'pcm_dtype': str(raw_pcm.dtype), 'duration_seconds': len(raw_pcm) / raw_fs,
        'pcm_to_pa': 'PCM_int16 / 32767 * 2 * sqrt(2)',
        'formal_fs_to_pa_coefficient': float(coefficient),
        'calibration_identity_max_absolute_error_pa': float(np.max(np.abs(physical - expected_physical))),
        'event_scope': 'full recording, all original frames',
        'remove_dc': False, 'clipping': False, 'normalization': False,
        'resampling': False, 'alignment_or_curve_fit': False,
        'execution_seconds': perf_counter() - started,
    }


def test_all_eight_new_files_match_fixed_official_blobs_sizes_and_sha256():
    checked_manifest()


@pytest.mark.parametrize('signal_id', [2, 3, 4])
def test_stationary_waveform_formal_import_calibration_total_and_240_specific(signal_id):
    receipt = evaluate_stationary_case(signal_id)
    assert receipt['passed'], receipt


def write_validation_receipt():
    started = perf_counter()
    manifest, records = checked_manifest()
    cases = [evaluate_stationary_case(signal_id) for signal_id in CASES]
    b2_reference = np.loadtxt(REF / 'third_octave_signal1_specific.csv', skiprows=1, encoding='utf-8-sig')
    assert b2_reference.shape == (240,) and np.all(np.isfinite(b2_reference))
    receipt = {
        'schema_version': 1, 'passed': all(case['passed'] for case in cases),
        'executed_at_utc': datetime.now(timezone.utc).isoformat(),
        'execution_seconds': perf_counter() - started,
        'repository': manifest['repository'], 'tag': 'v1.2.1', 'commit': COMMIT,
        'official_blob_size_sha256_integrity': {'passed': True, 'files_checked': 8},
        'reference_provenance_sha256': PROVENANCE, 'mosqito_version': version('mosqito'),
        'gates_frozen_before_first_numerical_run': GATES, 'cases': cases,
        'b2_signal1': {
            'acquired_and_integrity_verified': True, 'product_validation': False,
            'library_algorithm_test_executed': False, 'input_type': 'third_octave_levels',
            'input_sha256': records['third_octave_signal1.source.txt']['sha256'],
            'reference_sha256': records['third_octave_signal1_specific.csv']['sha256'],
            'reference_specific_values': len(b2_reference), 'upstream_Nexpected_sone': 83.296,
            'remaining_condition': 'The product has no third-octave-level input entry point.',
        },
        'scope': 'Three stationary B3 complete waveforms through formal product import/calibration/compute_stationary; B2 acquisition only.',
        'not_claimed': ['Complete ISO compliance', 'Diffuse-field validation', 'B2 product input coverage', 'Independent real microphone calibration'],
        'distribution': manifest['distribution'],
    }
    destination = ROOT / 'artifacts/loudness_stationary_extended_validation.json'
    destination.parent.mkdir(exist_ok=True)
    destination.write_text(json.dumps(receipt, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print(json.dumps({'passed': receipt['passed'], 'path': str(destination), 'cases': len(cases)}, ensure_ascii=False))
    return receipt


if __name__ == '__main__':
    raise SystemExit(0 if write_validation_receipt()['passed'] else 1)
